# Generated by Django 5.2 on 2025-04-04 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="TodoItem",
        ),
    ]
